apps/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from drf_yasg import openapi
from rest_framework import permissions
from drf_yasg.views import get_schema_view


schema_view = get_schema_view(
    openapi.Info(
        title = "My API",
        default_version = 'V1',
        description = 'Swagger documentation',
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('music/', include('music.urls', namespace='music')),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', include('registration.urls', namespace='registration')),

    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('blog_api/', include('blog_api.urls', namespace='blog_api')),

]

urlpatterns += [
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc",
        ),

        re_path( r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#  Settings Django Debug Toolbar START
# from django.urls import path, include
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]
#  Settings Django Debug Toolbar FINISH

blog/urls.py
from django.urls import path
from .views import posts, post_detail, add_post, edit_post, delete_post, send_email_back

app_name = 'blog'

urlpatterns = [
    path('', posts, name='posts'),
    path('post/<int:id>/', post_detail, name='post_detail'),
    path('add_post/', add_post, name='add_post'),
    path('edit/<int:id>/', edit_post, name='edit_post'),
    path('delete/<int:id>/', delete_post, name='delete_post'),
    path('send_email_back/', send_email_back, name='send_email_back'),
]

blog/models.py
from django.db import models
from django.conf import settings

from datetime import datetime
now = datetime.now()
formatted_date_time = now.strftime("%d.%m.%y %H:%M")



class Post(models.Model):
    title = models.CharField(max_length=100, blank=False, verbose_name="Заголовок")
    body = models.TextField(blank=False, verbose_name="Статья")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Автор")
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Категория")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    image = models.ImageField(upload_to='blog/post_images/', blank=True, null=True, verbose_name="Изображение")

    class Meta:
        verbose_name = '1. Статья'
        verbose_name_plural = '1. Статьи'



class Category(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '2. Категория'
        verbose_name_plural ='2. Категории'

blog/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'category', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок статьи'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Введите текст статьи'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file', 'id': 'image-input'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['title'].label = 'Заголовок статьи'
            self.fields['body'].label = 'Текст статьи'
            self.fields['category'].label = 'Категория'
            self.fields['image'].label = 'Изображение'

blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post, Category
from .forms import PostForm
from .tasks import send_email_async



def posts(request):
    title = 'Статьи'
    categories = Category.objects.all()
    category_id = request.GET.get('category')
    query = request.GET.get('q') #111
    posts = Post.objects.all().order_by(('-created_at'))
    if category_id:
        posts = posts.filter(category_id=category_id)
    if query:
        posts = Post.objects.filter(
            Q(title__icontains=query) |
            Q(body__icontains=query)
        ).distinct()


    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'title': title, 'categories': categories, 'page_obj': page_obj}
    return render(request, 'posts.html', context)



@login_required(login_url='/registration/login/')
def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'post_detail.html', {'post': post})


@login_required(login_url='/registration/login/')
def add_post(request):
    title = 'Страница добавления статьи'
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:posts')
    else:
        form = PostForm()
    return render(request, 'add_post.html', {'form': form, 'title': title})



@login_required(login_url='/registration/login/')
def edit_post(request, id):
    title = 'Страница редактирования статьи'
    post = get_object_or_404(Post, id=id)
    if post.author != request.user and not request.user.is_superuser:
        return render(request, 'action_prohibited.html')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
            return redirect('blog:posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form, 'post': post, 'title': title})




@login_required(login_url='/registration/login/')
def delete_post(request, id):
    title = 'Подтверждение удаления'
    post = get_object_or_404(Post, id=id)

    if post.author != request.user:
        return render(request, 'action_prohibited.html')
    if request.method == 'POST':
        post.delete()
        return redirect('blog:posts')
    return render(request, 'delete_confirmation.html', {'post': post})


@login_required(login_url='/registration/login/')
def send_email_back(request):
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        recipient_list = ['alex.ponomarov@mail.ru']

        send_email_async.delay(subject, message, recipient_list)

        return render(request, 'email_sent_successfully.html')
    else:
        return render(request, 'send_email.html')

blog/templates/action_prohibited.html
{% extends "base.html" %}

{% block content %}

<div class="wrapper">
    <h1  style="color:red;  margin-bottom: 100px;" class="title_page">Действие запрещено.</h1>
    <div style="margin-bottom: 100px;" class="paragraph">Вы не можете производить это действие!</div>
    <div><a class="buttonSimp"  href="{% url 'blog:posts' %}">На главную</a></div>
</div>
{% endblock %}

blog/templates/add_post.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
        <h1 style="margin-bottom: 50px;" class="title_page">{{ title }}</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

                <!-- {{ form.as_p }}-->

                <div class="form-group">
                    <label class="labelEditAddPost" for="id_title">Заголовок:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="id_body">Текст поста:</label>
                    {{ form.body }}
                </div>
                <div class="form-group">
                    <label for="id_category">Категория:</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label for="id_image">Изображение:</label>
                    {{ form.image }}
                </div>



            <div style="margin-top: 150px;" class = 'pageAddPostButton'>
                <div><button class="buttonSimpForm" type="submit">Добавить статью</button></div>
                <div><a class="buttonSimp" href="{% url 'blog:posts' %}">На главную</a></div>
            </div>
        </form>
</div>
{% endblock %}

blog/templates/delete_confirmation.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
    <h1>{{ title }}</h1>
    <h1 class="title_page" style="color:red; margin-top: 150px; margin-bottom: 350px;">Вы действительно хотите удалить пост "{{ post.title }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <div class = 'pageEditPostButton'>
            <div><a class="buttonSimp"  href="{% url 'blog:posts' %}">Нет, вернуться назад</a></div>
            <div><button class="buttonDel"  type="submit">Да, удалить</button></div>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/edit_post.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
    <h1 style="margin-bottom: 50px;" class="title_page">{{ title }}</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
<!--        {{ form.as_p }}-->

            <div class="form-group">
                <label class="labelEditAddPost" for="id_title">Заголовок:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_body">Текст поста:</label>
                {{ form.body }}
            </div>
            <div class="form-group">
                <label for="id_category">Категория:</label>
                {{ form.category }}
            </div>
            <div class="form-group">
                <label for="id_image">Изображение:</label>
                {{ form.image }}
            </div>

        <div style="margin-top: 100px;" class = 'pageEditPostButton'>
            <div><button class="buttonSimpForm" type="submit">Сохранить изменения</button></div>
            <div><a class="buttonSimp" href="{% url 'blog:posts' %}">На главную</a></div>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/email_sent_successfully.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
    <h1 style="color:green; margin-top: 50px; margin-bottom: 150px;" class="title_page">Письмо успешно отправлено!</h1>
    <p style="font-size: 18px;  text-align: center; margin-bottom: 350px;">Письмо успешно отправлено!</p>
    <a class="buttonSimp" href="/">Вернуться на главную страницу</a>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}

<div class="wrapper">
  <div class="post__card-wrapper">
        <h2 class="post__title-detail">{{post.title}}</h2>
        <div class="post__body">{{post.body}}</div>
            {% if post.image %}
            <div class="post_detail__img"><img class="post_detail__img_img" src="{{ post.image.url }}" alt="{{ post.name }}"></div>
            {% endif %}

        <div class="post_info-blok">
            <div class="post_info">Автор публикации: {{post.author}}</div>
            <div class="post_info">Категория: {{post.category}}</div>
            <div class="post_info">Дата публикации: {{post.created_at|date:"d.m.y H:i"}}</div>
        </div>

        <div class="post_choice-menu">
            <div><a class="buttonSimp"  href="{% url 'blog:posts' %}">На главную</a></div>
            <div><a class="buttonSimp" href="{% url 'blog:edit_post' post.id %}">Редактировать пост</a></div>
            <div><a class="buttonSimp"  href="{% url 'blog:send_email_back' %}">Отправить сообщение администратору</a></div>
            <div><a class="buttonSimp" href="{% url 'blog:delete_post' post.id %}">Удалить пост</a></div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/posts.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="wrapper">
    <div class="posts__title-box">
        <div><h1 class="title_page_blog title_page">{{ title }}</h1></div>
        <div><a class="button__add-post" href="{% url 'blog:add_post' %}">Добавьте свою статью</a></div>
    </div>

       <!-- ПОЛЕ ПОИСКА СТАТЬИ СТАРТ -->
    <form method="get" class="search-form">
        <div class="search-container">
            <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Поиск по названию статьи или слову в статье..."
                   class="search-input">
            <button class="search-button" type="submit">🔍 Найти</button>
        </div>
    </form>
   <!-- ПОЛЕ ПОИСКА СТАТЬИ ФИНИШ -->

    <!-- ФИЛЬТР ПО КАТЕГОРИЯМ СТАРТ -->
    <div class="post__category_styles">
        <strong>Категории:</strong>
        <a class="post__category_buttons" href="{% url 'blog:posts' %}" class="xxx">Все</a>
        {% for category in categories %}
            <a class="post__category_buttons" href="?category={{ category.id }}" class="xxx">
                {{ category.name }}
            </a>
        {% endfor %}
    </div>
    <!-- ФИЛЬТР ПО КАТЕГОРИЯМ ФИНИШ -->

    <!-- СТАТЬИ СТАРТ -->
    <div class="post__cards-wrapper">
        {% for post in page_obj %}
            <div class="post__card-wrapper">
                    <div class="post__title-box">
                        <div><h2 class="post__title-all">{{post.title}}</h2></div>
                        <div><a class="post__button-more" href="{% url 'blog:post_detail' post.id %}">Подробнее</a></div>
                    </div>
                    <div class="post__body-img-wrapper">
                        <div class="post__body">{{post.body}}<div>
                        {% if post.image %}
                        <div class='post__img'><img class='post__img_img' src="{{ post.image.url }}" alt="{{ post.name }}"></div>
                        {% endif %}
                    </div>
                    <div class="post_info-blok">
                        <div class="post_info">Автор публикации: {{post.author}}</div>
                        <div class="post_info">Категория: {{post.category}}</div>
                        <div class="post_info">Дата публикации: {{post.created_at|date:"d.m.y H:i"}}</div>
                    </div>
            </div>
        {% endfor %}
    </div>
    <!-- СТАТЬИ ФИНИШ -->

    <!-- ПАГИНАЦИЯ СТАРТ -->
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a></li>
        {% endif %}
        {% for num_page in page_obj.paginator.page_range %}
          {% if num_page == page_obj.number %}
              <li class="page-item active"><a class="page-link" href="#">{{ num_page }}</a></li>
          {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a></li>
        {% endif %}
      </ul>
    </nav>
    <!-- ПАГИНАЦИЯ ФИНИШ -->

</div>
{% endblock %}

blog/templates/send_email.html
{% extends "base.html" %}

{% block content %}
<div class="wrapper">
    <title>Отправка письма</title>
    <h1 style="margin-bottom: 50px;" class="title_page">Отправьте нам письмо!</h1>
    <!-- Используем метод POST -->


    <form class="send_emailForm" method="post" action="{% url 'blog:send_email_back' %}">
        {% csrf_token %}
        <label for="subject">Тема:</label>
        <input class="textForm" type="text" id="subject" name="subject">

        <label  class="label_send_emailForm" for="message" >Сообщение:</label>
        <textarea style="margin-bottom: 50px;" class="textareaForm" id="message" name="message" placeholder='Приветствую. Хотел бы ...'></textarea>

        <button class="buttonSimpForm out_forButtonUp" type="submit">Отправить письмо</button>
    </form>
</div>
{% endblock %}