apps/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from drf_yasg import openapi
from rest_framework import permissions
from drf_yasg.views import get_schema_view


schema_view = get_schema_view(
    openapi.Info(
        title = "My API",
        default_version = 'V1',
        description = 'Swagger documentation',
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('music/', include('music.urls', namespace='music')),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', include('registration.urls', namespace='registration')),

    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('blog_api/', include('blog_api.urls', namespace='blog_api')),

]

urlpatterns += [
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc",
        ),

        re_path( r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#  Settings Django Debug Toolbar START
# from django.urls import path, include
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]
#  Settings Django Debug Toolbar FINISH

shop/urls.py
from django.urls import path, include
from .views import products_view, product_detail, cart_view, add_to_cart, remove_from_cart, delete_selected_products, \
    create_order, send_email_sell, order_is_sent, checkout_success, mark_items_as_selected, \
    pre_order, pre_order_confirmation, error_confirm_order, handler404, handler500

app_name = 'products'

urlpatterns = [
    path('', products_view, name='products'),

    path('product/<int:pk>/', product_detail, name='product_detail'),

    path('products_cart/', cart_view, name='cart_view'),
    path('products_cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),

    path('delete_selected/', delete_selected_products, name='delete_selected'),   # Новый путь для массового удаления

    path('products_cart/remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('products/mark_items_as_selected/', mark_items_as_selected, name='mark_items_as_selected'),
    path('products/pre_order/', pre_order, name='pre_order'),
    path('products/pre_order_confirmation/', pre_order_confirmation, name='pre_order_confirmation'),

    path('products/create_order/', create_order, name='create_order'),

    path('products/send_email_sell/<int:order_id>/', send_email_sell, name='send_email_sell'),


    path('products/order_is_sent/', order_is_sent, name='order_is_sent'),
    path('products/checkout_success/', checkout_success, name='checkout_success'),
    path('products/error_confirm_order/', error_confirm_order, name='error_confirm_order'),


]

shop/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import Product, Category, CurrencyRateUSD, CurrencyRateEUR, CartItem, Order, Seller, OrderDetail
import logging
from pathlib import Path
from django.shortcuts import render, redirect
from .tasks import send_customer_email, send_admin_new_order_email, clean_cart


BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / 'shop' / 'log_file'

if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True)

CART_LOG_PATH = LOG_DIR / 'log_cart.log'

cart_logger = logging.getLogger('cart')
cart_logger.setLevel(logging.DEBUG)

cart_handler = logging.FileHandler(CART_LOG_PATH)
cart_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
cart_logger.addHandler(cart_handler)



def products_view(request):
    title = 'Магазин'
    categories = Category.objects.all()
    category_id = request.GET.get('category')
    query = request.GET.get('q')

    rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
    rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()

    products = Product.objects.all().order_by('name')
    filtered_products = products

    if category_id:
        filtered_products = filtered_products.filter(category_id=category_id)

    if query:
        filtered_products = filtered_products.filter(name__icontains=query)

    paginator = Paginator(filtered_products, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'products.html', {
        'page_obj': page_obj,
        'categories': categories,
        'selected_category': category_id,
        'title': title,
        'rate_usd': rate_usd,
        'rate_eur': rate_eur,
    })

@login_required(login_url='/registration/login/')
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)

    rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
    rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()

    return render(request, 'product_detail.html', {
        'product': product,
        'rate_usd': rate_usd,
        'rate_eur': rate_eur,
    })



@login_required(login_url='/registration/login/')
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        requested_quantity = int(request.POST.get('quantity', 1))
        existing_cart_items = CartItem.objects.filter(user=request.user, product=product)

        current_total_quantity = sum(item.quantity for item in existing_cart_items) + requested_quantity

        if current_total_quantity > product.quantity:
            return redirect('products:cart_view')

        for cart_item in existing_cart_items:
            cart_item.quantity += requested_quantity
            cart_item.save()
            break
        else:
            CartItem.objects.create(user=request.user, product=product, quantity=requested_quantity)

        return redirect('products:cart_view')
    else:
        context = {'product': product}
        return render(request, 'add_to_cart_form.html', context)



@login_required(login_url='/registration/login/')
def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = CartItem.objects.get(user=request.user, product=product)
        cart_item.delete()
        cart_logger.info(f"Товар -> '{product.name}' успешно удалён из корзины.")
    except CartItem.DoesNotExist:
        cart_logger.info(f"Ошибка удаления товара {product.name} из корзины")
    return redirect('products:cart_view')


@login_required(login_url='/registration/login/')
def delete_selected_products(request):
    if request.method == 'POST':
        selected_items = request.POST.getlist('selected_item', [])
        if not selected_items:
            return redirect('products:cart_view')
        selected_items = map(int, selected_items)
        items = CartItem.objects.filter(pk__in=selected_items, user=request.user)
        names = ', '.join([item.product.name for item in items])
        items.delete()

        cart_logger.info(f"Выбранные товары ({names}) были успешно удалены из вашей корзины.")
    return redirect('products:cart_view')



@login_required(login_url='/registration/login/')
def cart_view(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total = sum(item.total_price() for item in cart_items)
    rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
    rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()
    return render(request, 'products_cart.html',
                  {'products': cart_items, 'total': total,'rate_usd': rate_usd, 'rate_eur': rate_eur,})



@login_required(login_url='/registration/login/')
def pre_order(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total = sum(item.total_price() for item in cart_items)
    rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
    rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()
    return render(request, 'pre_order.html',
                  {'products': cart_items, 'total': total,'rate_usd': rate_usd, 'rate_eur': rate_eur,})



@login_required(login_url='/registration/login/')
def mark_items_as_selected(request):
    if request.method == 'POST':
        all_user_cart_items = list(CartItem.objects.filter(user=request.user))

        selected_items_ids = request.POST.getlist('selected_item', [])

        for item in all_user_cart_items:
            if str(item.pk) in selected_items_ids:
                item.selected = True
            else:
                item.selected = False
            item.save()

        return redirect('products:pre_order')
    return None



@login_required(login_url='/registration/login/')
def pre_order_confirmation(request):
    if request.method == 'POST':

        cart_items = CartItem.objects.filter(user=request.user, selected=True)
        total_amount = sum([item.total_price() for item in cart_items])

        rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
        rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()

        return render(request, 'pre_order_confirmation.html', {
            'products': cart_items,
            'total_amount': total_amount,
            'rate_usd': rate_usd,
            'rate_eur': rate_eur,
            'user': request.user,
        })

    else:
        return redirect('products:products')



@login_required(login_url='/registration/login/')
def create_order(request):
    if request.method == 'POST':
        cart_items = CartItem.objects.filter(user=request.user, selected=True)

        unavailable_products = []
        for item in cart_items:
            if item.product.quantity == 0 or not item.product.in_stock:
                unavailable_products.append(item.product.name)

        if unavailable_products:
            cart_logger.info(request, f"Следующие товары временно отсутствуют: {', '.join(unavailable_products)}")
            return redirect('products:pre_order')

        total_amount = sum([item.total_price() for item in cart_items])
        new_order = Order.objects.create(user=request.user, total_amount=total_amount)

        details = []
        for item in cart_items:
            detail = OrderDetail(
                order=new_order,
                product=item.product,
                quantity=item.quantity,
            )
            details.append(detail)
        OrderDetail.objects.bulk_create(details)

        order_items_list = OrderDetail.objects.filter(order=new_order)

        rate_usd = CurrencyRateUSD.objects.order_by('-created_at').first()
        rate_eur = CurrencyRateEUR.objects.order_by('-created_at').first()

        return render(request, 'order.html', {
            'order': new_order,
            'products': order_items_list,
            'rate_usd': rate_usd,
            'rate_eur': rate_eur,
            'order_id': new_order.pk,
            'total_amount': total_amount,
        })
    else:
        return redirect('products:cart_view')


@login_required(login_url='/registration/login/')
def send_email_sell(request, order_id):
    cart_logger.info("Завершающий этап оформления заказа: send_email_sell")
    try:
        # raise ValueError (f"переход на Exception для проверки products:error_confirm_order")
        with transaction.atomic():
            cart_logger.info("Начало работы  - send_email_sell")

            order = Order.objects.select_for_update().get(pk=order_id)

            if order.is_sent:
                messages.warning(request, "Этот заказ уже был обработан.")
                return redirect('products:order_is_sent')

            for order_item in order.details.all():
                product = order_item.product
                available_quantity = product.quantity
                purchased_quantity = order_item.quantity

                if available_quantity >= purchased_quantity:
                    product.quantity -= purchased_quantity
                    product.save()
                else:
                    raise ValueError(f"Товар '{product.name}' отсутствует в нужном количестве.")

            order.is_sent = True
            order.save()

            cart_logger.info("Старт отправки писем через Celery")
            send_customer_email.delay(order.id)
            send_admin_new_order_email.delay(order.id)

            cart_logger.info("Старт задачи на очистку корзины через Celery")
            clean_cart.delay(request.user.id, order_id)

            return redirect('products:checkout_success')

    except Exception as e:
        cart_logger.error(f"Произошла ошибка отправки писем: {e}")
        return redirect('products:error_confirm_order')

shop/templates/order.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
<div class="wrapper wrapper_shop">

      <div class="course_style">
        <div>Курс NBRB BYN/USD: {{ rate_usd.rate_usd|floatformat:2 }}</div>
        <div>Курс NBRB BYN/EUR: {{ rate_eur.rate_eur|floatformat:2 }}</div>
    </div>

    <h1 class="title_page title_page-order">3. Отправление заказа</h1>

    {% if products %}
        <table class="product__order-table">
            <thead class="product__order-table-header">
                <tr>
                    <th style="border:1px solid black;" class="product__order-table-header-product">Название товара</th>
                    <th style="border:1px solid black;" class="product__order-table-header-quantity">Количество</th>
                    <th style="border:1px solid black;" class="product__order-table-header-subtotal">Цена</th>
                    <th style="border:1px solid black;" class="product__order-table-header-subtotal">Стоимость</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td style="border:1px solid black;" class="product__cart_product-name">{{ product.product.name }}</td>
                        <td style="border:1px solid black;" class="product__cart_product-quantity">{{ product.quantity }}</td>
                        <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ product.product.price |mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                        <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ product.product.price |mul:product.quantity |mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="product__order-total-amount">
            <strong>Итого к оплате:</strong> {{ total_amount |mul:rate_usd.rate_usd|floatformat:2}} Br
        </div>

         <div class="product__empty-full-basket-wrapper">

            <form method="POST" action="{% url 'products:send_email_sell' order_id=order_id %}">
                {% csrf_token %}

                <button type="submit" class="product__button product__button-cont">Отравить заказ</button>
            </form>


             <div><a href="{% url 'products:cart_view' %}" class="product__button product__button-cont">Корзина</a></div>
        </div>

    {% else %}
        <div class="product__empty-full-basket-wrapper">
            <div class="product__description-empty-basket"><p>Нет товаров для оформления заказа.</p></div>
            <div><a href="{% url 'products:products' %}" class="product__button product__button-cont">Продолжить покупки</a></div>
        </div>
    {% endif %}
</div>
{% endblock %}

shop/templates/pre_order.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Корзина{% endblock %}

{% block content %}
<div class="wrapper wrapper_shop">

    <div class="course_style">
        <div>Курс NBRB BYN/USD: {{ rate_usd.rate_usd|floatformat:2 }}</div>
        <div>Курс NBRB BYN/EUR: {{ rate_eur.rate_eur|floatformat:2 }}</div>
    </div>

    <h1 class="title_page title_page-products-basket">1. Выберите товары для покупки</h1>
    </br>
    {% if products %}
        <form method="POST" action="{% url 'products:mark_items_as_selected' %}">
            {% csrf_token %}
            <label>
                <input type="checkbox" onclick="toggleCheckboxes(this)" /> Выделить всё

            </label>

            <table class="product__order-table">
                <thead class="product__order-table-header">
                    <tr>
                        <th style="border:1px solid black;" class="product__order-table-header-select">Чек</th>
                        <th style="border:1px solid black;" class="product__order-table-header-product">Наименование товара</th>
                        <th style="border:1px solid black;" class="product__order-table-header-quantity">Количество</th>
                        <th style="border:1px solid black;" class="product__order-table-header-subtotal">Цена</th>
                        <th style="border:1px solid black;" class="product__order-table-header-subtotal">Стоимость</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                        <tr>
                            <td style="border:1px solid black;" class="product__cart_product-checkbox">
                                <input type="checkbox" name="selected_item" value="{{ product.id }}"
                                      {% if product.selected %}checked{% endif %}>
                            </td>
                            <td style="border:1px solid black;" class="product__cart_product-name">{{ product.product.name }}</td>
                            <td style="border:1px solid black;" class="product__cart_product-quantity">{{ product.quantity }}</td>
                            <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ product.product.price |mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                            <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ product.total_price |mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>


            <button type="submit" class="product__button product__button-del">Подтвердите Ваш выбор товаров перед дальнейшим оформлением </button>
        </form>



        <script>
        function toggleCheckboxes(masterCheckbox) {
            const checkboxes = document.querySelectorAll('input[name="selected_item"]');
            checkboxes.forEach(checkbox => {
                checkbox.checked = masterCheckbox.checked;
            });
        }
        </script>



          <div><p class="product__order-total-amount">
                Итого в корзине:
                {{ total|mul:rate_usd.rate_usd|floatformat:2}} Br </br>
               {{ total }} $</br>
               {{ total|mul:rate_usd.rate_usd|div:rate_eur.rate_eur|floatformat:2}} €</br>
            </p></div>

        </br>
        <div class="product__empty-full-basket-wrapper">

            <form method="post" action="{% url 'products:pre_order_confirmation' %}">
                {% csrf_token %}
            <button type="submit" class="product__button product__button-cont">Продолжить оформление</button>
            </form>

            <a href="{% url 'products:cart_view' %}" class="product__button product__button-cont">Корзина</a>


            <a href="{% url 'products:products' %}" class="product__button product__button-cont">Продолжить покупки</a>
        </div>


    {% else %}
        <div class="product__empty-full-basket-wrapper">
            <div class="product__description-empty-basket"><p>Корзина пуста.</p></div>
            <div><a href="{% url 'products:products' %}" class="product__button product__button-cont">Продолжить покупки</a></div>
        </div>
    {% endif %}
</div>
{% endblock %}

shop/templates/pre_order_confirmation.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Подтверждение заказа{% endblock %}

{% block content %}
<div class="wrapper wrapper_shop">

    <div class="course_style">
        <div>Курс NBRB BYN/USD: {{ rate_usd.rate_usd|floatformat:2 }}</div>
        <div>Курс NBRB BYN/EUR: {{ rate_eur.rate_eur|floatformat:2 }}</div>
    </div>

    <h1 class="title_page title_page-pre-order">2. Подтверждение заказа</h1>
    </br>
    <p>Перед оформлением заказа проверьте, все ли товары вас устраивают</p>
    </br>

      <table class="product__order-table">
                <thead class="product__order-table-header">
                    <tr>
                        <th style="border:1px solid black;" class="product__order-table-header-product">Наименование товара</th>
                        <th style="border:1px solid black;" class="product__order-table-header-quantity">Количество</th>
                        <th style="border:1px solid black;" class="product__order-table-header-subtotal">Цена</th>
                        <th style="border:1px solid black;" class="product__order-table-header-subtotal">Стоимость</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in products %}
                        <tr>
                            <td style="border:1px solid black;" class="product__cart_product-name">{{ item.product.name }} </td>
                            <td style="border:1px solid black;" class="product__cart_product-quantity">{{ item.quantity }}</td>
                            <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ item.product.price |mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                            <td style="border:1px solid black;" class="product__cart_product-subtotal">{{ item.quantity|mul:item.product.price|mul:rate_usd.rate_usd|floatformat:2}} Br</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>



    <p class="product__order-total-amount">Общая стоимость выбранных товаров: {{ total_amount|mul:rate_usd.rate_usd|floatformat:2}} Br</p>
   </br>
    <div class="product__empty-full-basket-wrapper">



            <form method="post" action="{% url 'products:create_order' %}">
                {% csrf_token %}
                <button type="submit" class="product__button product__button-cont">Подтвердить заказ</button>
            </form>

        <a href="{% url 'products:pre_order' %}" class="product__button product__button-cont">на шаг назад</a>
        <a href="{% url 'products:cart_view' %}" class="product__button product__button-cont">Корзина</a>
    </div>

</div>
{% endblock %}

shop/templates/product_detail.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}

    <div class="wrapper wrapper_shop">

    <div class="course_style">
        <div>Курс NBRB BYN/USD: {{ rate_usd.rate_usd|floatformat:2 }}</div>
        <div>Курс NBRB BYN/EUR: {{ rate_eur.rate_eur|floatformat:2 }}</div>
    </div>

    <h1 class="title_page">{{ product.name }}</h1>


    <div class="product__card-wrapper">

        <div class="product__img-block">
            {% if product.image %}
                <img class="product__img-img" src="{{ product.image.url }}"  alt="{{ product.name }}">
            {% else %}
                <img class="product__img-img"src="{% static 'no-image.png' %}" alt="Нет фото">
            {% endif %}
        </div>


        <div class="product__card">

            <div class="product__card-container">
                <h2 class="product_card__name">{{ product.name }}</h2>
                <p class="product_card__description">{{ product.description }}</p>
                <p class="product_card__description">Производитель/Брэнд: {{ product.brand }}</p>
                <p class="product_card__description">Продавец: {{ product.seller }}</p>
                <p class="product_card__description">e-mail продавца: {{ product.seller.email }}</p>

                {% if product.image %}
                <p class="product_card__description">Скидка: {{ product.discount|floatformat:0 }} %</p>
                {% else %}

                {% endif %}

                    {% if product.price %}
                    <p class="product__price">
                           Цена: {{ product.price|mul:rate_usd.rate_usd|floatformat:2}} Br за {{ product.unit }}
                    </p>

                    <p class="product__price">
                            {{ product.price|mul:rate_usd.rate_usd|div:rate_eur.rate_eur|floatformat:2}} €
                    </p>

                    <p class="product__price">{{ product.price }} $</p>
                    {% else %}
                        <p class="product__price">Цена временно недоступна.</p>
                    {% endif %}

                    {% if product.in_stock %}
                        <span class="product__in-stock">В наличии {{product.quantity}} {{product.unit}}</span>
                    {% else %}
                        <span class="product__not-in-stock">Нет в наличии</span>
                    {% endif %}
            </div>



            <div class="product__card-buttons">

                <form method="post" action="{% url 'shop:add_to_cart' product.id %}">
                    {% csrf_token %}
                    <label for="quantity">Количество:</label>
                    <input class="product__detail-count" type="number" name="quantity" id="quantity" min="1" max="{{ product.quantity }}" required />
                     </br>
                    <button type="submit" class="product__button product__button-cont">Добавить в корзину</button>
                </form>

            </div>

            <a href="{% url 'shop:products' %}" class="product__button product__button-del">Назад к товарам</a>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/products.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}


{% block title %}Список товаров{% endblock %}

{% block content %}
<div class="wrapper wrapper_shop">
    <div class="products__title-box">
        <h1 class="title_page">{{ title }}</h1>
        <div><a class="product__button-cart" href="{% url 'products:cart_view' %}">Корзина 🛒</a></div>
    </div>

<div class="course_style">
    <div>Курс NBRB BYN/USD: {{ rate_usd.rate_usd|floatformat:2 }}</div>
    <div>Курс NBRB BYN/EUR: {{ rate_eur.rate_eur|floatformat:2 }}</div>
</div>

    <!-- CODE SEARCH START -->
    <form method="get" class="search-form">
        <div class="search-container">
            <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Поиск названию товара..." class="search-input">
            <button class="search-button" type="submit">🔍 Найти</button>
        </div>
    </form>
    <!-- CODE SEARCH END -->

    <!-- CODE CATEGORY START -->

    <div class="shop_category__styles">
        <strong>Категории:</strong>
        <a  class="shop_category__buttons"href="{% url 'shop:products' %}">Все</a>
        {% for category in categories %}

        <a class="shop_category__buttons" href="{% url 'shop:products' %}?category={{ category.id }}">
            {{ category.name }}
        </a>
        {% endfor %}
    </div>

    <!-- CODE CATEGORY END -->

    <!-- CODE PRODUCT START -->

    <div class="shop__cards-wrapper">
        {% for product in page_obj %}
            <div class="shop__card-wrapper">
                {% if product.image %}
                    <img class='products__card_img' src="{{ product.image.url }}" alt="{{ product.name}}">
                {% else %}
                    <img class='products__card_img' src="{% static 'no-image.png' %}" alt="Нет фото">
                {% endif %}

                <div class="card-body">
                    <h5 class="product__name">{{ product.name |truncatewords:3  }}</h5>

                    <div class="card-footer">
                            {% if product.price %}

                                <p class="product__price">
                                        {{ product.price|mul:rate_usd.rate_usd|floatformat:2}} Br
                                </p>

                                <p class="product__price">
                                        {{ product.price|mul:rate_usd.rate_usd|div:rate_eur.rate_eur|floatformat:2}} €
                                </p>

                                <p class="product__price">{{ product.price }} $</p>
                            {% else %}
                                <p class="product__price">Цена временно недоступна.</p>
                            {% endif %}

                            {% if product.in_stock %}
                                <span class="product__in-stock">В наличии {{product.quantity}} {{product.unit}}</span>
                            {% else %}
                                <span class="product__not-in-stock">Нет в наличии</span>
                            {% endif %}

                            <div class="product__more">
                                <a class="product__button-more" href="{% url 'products:product_detail' product.id %}">Подробнее</a>
                            </div>
                    </div>


                </div>
            </div>
        {% empty %}
            <p class="product__alert">Нет доступных товаров.</p>
        {% endfor %}
    </div>
    <!-- CODE PRODUCT END -->

    <!-- CODE PAGINATION START -->
    <nav>
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">Предыдущая</a></li>
        {% endif %}
        {% for num_page in page_obj.paginator.page_range %}
            {% if num_page == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ num_page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}">Следующая</a></li>
        {% endif %}
        </ul>
    </nav>
    <!-- CODE PAGINATION END -->

</div>
{% endblock %}