apps/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from drf_yasg import openapi
from rest_framework import permissions
from drf_yasg.views import get_schema_view


schema_view = get_schema_view(
    openapi.Info(
        title = "My API",
        default_version = 'V1',
        description = 'Swagger documentation',
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('music/', include('music.urls', namespace='music')),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', include('registration.urls', namespace='registration')),

    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('blog_api/', include('blog_api.urls', namespace='blog_api')),

]

urlpatterns += [
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc",
        ),

        re_path( r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#  Settings Django Debug Toolbar START
# from django.urls import path, include
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]
#  Settings Django Debug Toolbar FINISH

blog/urls.py
from django.urls import path
from .views import posts, post_detail, add_post, edit_post, delete_post, send_email_back

app_name = 'blog'

urlpatterns = [
    path('', posts, name='posts'),
    path('post/<int:id>/', post_detail, name='post_detail'),
    path('add_post/', add_post, name='add_post'),
    path('edit/<int:id>/', edit_post, name='edit_post'),
    path('delete/<int:id>/', delete_post, name='delete_post'),
    path('send_email_back/', send_email_back, name='send_email_back'),
]

music/urls.py
from django.urls import path
from .views import music, artist_songs_view, toggle_vote

app_name = 'music'

urlpatterns = [
    path('', music, name='music'),
    path('artist/<int:artist_id>/songs/', artist_songs_view, name='artist_songs_view'),

    # path('toggle_vote/', toggle_vote, name='toggle_vote'),  # Назначение маршрута
    path('toggle_vote/<str:model_type>/<int:object_id>/<str:vote_type>/', toggle_vote, name='toggle_vote'),

]

registration/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import register_view
# from .apps.shop_api.views import RegisterAPIView, LogoutAPIView

app_name = 'registration'

urlpatterns = [

path('register/', register_view, name='register'),
path('login/', LoginView.as_view(template_name='login.html'), name='login'),
path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

# path('register/', RegisterAPIView.as_view(), name='api_register'),
# path('logout/', LogoutAPIView.as_view(), name='api_logout'),
]

shop/urls.py
from django.urls import path, include
from .views import products_view, product_detail, cart_view, add_to_cart, remove_from_cart, delete_selected_products, \
    create_order, send_email_sell, order_is_sent, checkout_success, mark_items_as_selected, \
    pre_order, pre_order_confirmation, error_confirm_order, handler404, handler500

app_name = 'products'

urlpatterns = [
    path('', products_view, name='products'),

    path('product/<int:pk>/', product_detail, name='product_detail'),

    path('products_cart/', cart_view, name='cart_view'),
    path('products_cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),

    path('delete_selected/', delete_selected_products, name='delete_selected'),   # Новый путь для массового удаления

    path('products_cart/remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('products/mark_items_as_selected/', mark_items_as_selected, name='mark_items_as_selected'),
    path('products/pre_order/', pre_order, name='pre_order'),
    path('products/pre_order_confirmation/', pre_order_confirmation, name='pre_order_confirmation'),

    path('products/create_order/', create_order, name='create_order'),

    path('products/send_email_sell/<int:order_id>/', send_email_sell, name='send_email_sell'),


    path('products/order_is_sent/', order_is_sent, name='order_is_sent'),
    path('products/checkout_success/', checkout_success, name='checkout_success'),
    path('products/error_confirm_order/', error_confirm_order, name='error_confirm_order'),


]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">


<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/zero_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

<!--    <link rel="stylesheet" href="{% static 'blog/css/style_blog.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'shop/css/style_shop.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'music/css/style_music.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'registration/css/style_registration.css' %}">-->

    <link rel="stylesheet" href="{% static 'css/pagination_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons_style.css' %}">

    <link rel="stylesheet" href="{% static 'css/style_blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_shop.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_music.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_registration.css' %}">

</head>
<body class="body__base">
    <header class="header">
            <div class="menu">
                <div><img src="{% static 'svg/christmas-tree-svgrepo-com.svg' %}" style="width: 45px;" alt="Christmas tree"></div>
                <div><a class="button__menu button__menu-first" href="{% url 'blog:posts' %}">Статьи</a></div>
                <div><a class="button__menu" href="{% url 'shop:products' %}">Магазин</a></div>
                <div><a class="button__menu" href="{% url 'music:music' %}">Музыка</a></div>
            </div>

            <div class="logo">
                  <img class="logo_img"src="{% static 'svg/logo.svg' %}"  alt="logo">
            </div>
            <div class="menu_register">
                {% if user.is_authenticated %}
                    <div class="menu_auth_name"><pre>Вы зарегистрированы как:
                        <b>{{ user.username }}</b></pre>
                    </div>
                    <div>
                        <form method="post" action="{% url 'registration:logout' %}">
                            {% csrf_token %}
                            <button class="button__menu button__menu-last" type="submit">Выйти</button>
                        </form>
                    </div>
                {% else %}
                    <div><a class="button__menu" href="{% url 'registration:login' %}">Войти</a></div>
                    <div><a class="button__menu button__menu-last" href="{% url 'registration:register' %}">Регистрация</a></div>
                {% endif %}
                 <div><img src="{% static 'svg/christmas-tree-svgrepo-com.svg' %}" style="width: 45px;" alt="Christmas tree"></div>
            </div>
    </header>

    <div class="container">
        <main>

                {% block content %}
                <!-- Здесь дочерние шаблоны вставят свой HTML -->
                {% endblock %}

        </main>

        <footer class=footer>
            <div class="footer__wrapper">
                <div class="footer__left-part">
                    <p>© 2025 Учебный проект Django BlogShopMusic:</p>
                    <p>Alpono24</p>
                    <p>alex.ponovarov@mail.ru</p>
                </div>

                <div class="footer__right-part"><a class="button-feedback"  href="{% url 'blog:send_email_back' %}">Обратная связь</a></div>
            </div>
        </footer>
    </div>
</body>

</html>