apps/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from drf_yasg import openapi
from rest_framework import permissions
from drf_yasg.views import get_schema_view


schema_view = get_schema_view(
    openapi.Info(
        title = "My API",
        default_version = 'V1',
        description = 'Swagger documentation',
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('music/', include('music.urls', namespace='music')),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', include('registration.urls', namespace='registration')),

    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('blog_api/', include('blog_api.urls', namespace='blog_api')),

]

urlpatterns += [
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc",
        ),

        re_path( r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



#  Settings Django Debug Toolbar START
# from django.urls import path, include
# if settings.DEBUG:
#     import debug_toolbar
#
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]
#  Settings Django Debug Toolbar FINISH

music/urls.py
from django.urls import path
from .views import music, artist_songs_view, toggle_vote

app_name = 'music'

urlpatterns = [
    path('', music, name='music'),
    path('artist/<int:artist_id>/songs/', artist_songs_view, name='artist_songs_view'),

    # path('toggle_vote/', toggle_vote, name='toggle_vote'),  # Назначение маршрута
    path('toggle_vote/<str:model_type>/<int:object_id>/<str:vote_type>/', toggle_vote, name='toggle_vote'),

]

music/models.py
from django.db import models
from django.contrib.auth.models import User

class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '1. Жанр'
        verbose_name_plural = '1. Жанры'




class Artist(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='music/artists/', blank=True, null=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '2. Артист / Группа'
        verbose_name_plural = '2. Артисты / Группы'



class Album(models.Model):
    title = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='albums')
    cover = models.ImageField(upload_to='music/albums/', blank=True, null=True)
    release_year = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.title} — {self.artist.name}"

    class Meta:
        verbose_name = '3. Альбом'
        verbose_name_plural = '3. Альбомы'



class Song(models.Model):
    title = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='songs')
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, blank=True, null=True, related_name='songs')
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, blank=True, null=True)
    audio_file = models.FileField(upload_to='music/songs/', blank=True, null=True)

    def __str__(self):
        return f"{self.title} — {self.artist.name}"

    class Meta:
        verbose_name = '4. Песня'
        verbose_name_plural = '4. Песни'
    


    
class Vote(models.Model):
    LIKE_CHOICES = [
        ('like', 'Like'),
        ('dislike', 'Dislike'),
    ]

    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name='votes', blank=True, null=True)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='votes', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=10, choices=LIKE_CHOICES)

    class Meta:
        unique_together = ['song', 'album', 'user']

    def __str__(self):
        if self.song:
            return f'{self.user.username}: {self.vote_type} for "{self.song.title}"'
        elif self.album:
            return f'{self.user.username}: {self.vote_type} for "{self.album.title}"'
        else:
            return ''

music/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render
from django.http import JsonResponse
from .models import Genre, Song, Album, Artist, Vote



@login_required(login_url='/registration/login/')
def music(request):
    title = "Музыка"
    genres = Genre.objects.all()
    genre_id = request.GET.get('genre')
    query = request.GET.get('q')
    songs = Song.objects.all()
    albums = Album.objects.all()
    artists = Artist.objects.all()
    if genre_id:
        songs = songs.filter(genre_id=genre_id)
    if query:

        songs = Song.objects.filter(
            Q(title__icontains=query) |
            Q(artist__name__icontains=query) |
            Q(album__title__icontains=query) |
            Q(genre__name__icontains=query)
        ).distinct()

    return render(request, 'music.html', {
        'songs': songs,
        'genres': genres,
        'albums': albums,
        'artists': artists,
        'selected_genre': genre_id,
        'title': title
    })




@login_required(login_url='/registration/login/')
def artist_songs_view(request, artist_id):
    artist = get_object_or_404(Artist, id=artist_id)
    songs = Song.objects.filter(artist=artist)
    number_of_songs = songs.count()  # Уже имеем queryset песен, считаем их сразу

    context = {
        'artist': artist,
        'songs': songs,
        'number_of_songs': number_of_songs,
    }
    
    return render(request, 'artist_songs.html', context)




@login_required(login_url='/registration/login/')
def toggle_vote(request, model_type, object_id, vote_type):
    """
    Обрабатывает AJAX-запрос для голосования.
    Определяет, является ли это лайком или дизлайком и создает или обновляет соответствующую запись.
    """
    if request.method == 'POST':
        obj = None
        if model_type == 'song':
            obj = get_object_or_404(Song, pk=object_id)
        elif model_type == 'album':
            obj = get_object_or_404(Album, pk=object_id)

        try:
            existing_vote = Vote.objects.get(
                user=request.user,
                song=obj if isinstance(obj, Song) else None,
                album=obj if isinstance(obj, Album) else None
            )

            if existing_vote.vote_type != vote_type:
                existing_vote.vote_type = vote_type
                existing_vote.save()
            else:
                existing_vote.delete()

        except Vote.DoesNotExist:
            new_vote = Vote(
                song=obj if isinstance(obj, Song) else None,
                album=obj if isinstance(obj, Album) else None,
                user=request.user,
                vote_type=vote_type
            )
            new_vote.save()

        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'error'}, status=400)

music/templates/artist_songs.html
{% extends "base.html" %}
{% load static %}
{% block title %}Музыка{% endblock %}
{% block content %}


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>



<div class="wrapper wrapper_music_detail">

   
        <div class="artist_blok-title">
            <div class="artist_blok-title-img">
                <img class="artist_img" src="{{ artist.image.url  }}"  alt="{{ album.title }}">
            </div>  

            <div class="artist_blok-title-text">
                <div><h1 class="artist_songs-title">{{ artist.name }}</h1></div>
                <div class="artist_songs-number">Количество песен: {{ number_of_songs }}</div>
            </div>

            <div class="artist_songs-back">
               <a class="artist_songs-back-btn" href="{% url 'music:music' %}">Назад</a> 
            </div>

        </div>

        {% for song in songs %}
        <div class="artist_song-wrapper"> 
            <div class="artist_song-audio">
                    {% if song.audio_file %}
                    <audio  class="music__song-audio" controls preload="none">
                        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                        Ваш браузер не поддерживает аудио.
                    </audio>
                {% else %}
                    <p class="music__song-audio-absent">Аудиофайл отсутствует</p>
                {% endif %}
            </div>
            <div class="artist_song-info">
                    <p class="artist_song-info-artist">{{ song.artist }}</p>
                    <p class="artist_song-info-artist">{{ song.title }}</p>
                    <p class="artist_song-info-artist">Альбом: {{ song.album.title|default:"нет альбома" }}</p> 
            </div>

            <!-- <div class="artist_songs-like">Like <a href="#" data-type="song" data-id="{{ song.id }}" data-vote="like" class="btn-like">💖</a></div>
            <div class="artist_songs-dislike">Dislike <a href="#" data-type="song" data-id="{{ song.id }}" data-vote="dislike" class="btn-dislike">👎</a></div> -->
<!--            <div class="artist_songs-add-to-playlist"></div>-->
<!--              <div class="artist_songs-like">-->
<!--                  Like <a href="#" data-type="song" data-id="{{ song.id }}" data-vote="like" class="btn-like">💖</a>-->
<!--              </div>-->
<!--              <div class="artist_songs-dislike">-->
<!--                  Dislike <a href="#" data-type="song" data-id="{{ song.id }}" data-vote="dislike" class="btn-dislike">👎</a>-->
<!--              </div>-->
          </div> 

        {% empty %}
            <p class="music__song-audio-absent">У этого исполнителя пока нет песен.</p>
        {% endfor %}


  </div>
{% endblock %}

music/templates/music.html
{% extends "base.html" %}
{% load static %}
{% block title %}Музыка{% endblock %}
{% block content %}
<div class="wrapper wrapper_music">
    <h1 class="title_page title_page_music">{{ title }}</h1>

   <!-- ПОЛЕ ПОИСКА ПЕСНИ СТАРТ -->
    <form method="get" class="search-form">
        <div class="search-container">
            <input type="text" name="q" value="{{ request.GET.q }}" placeholder="Что хочешь включить?"
                   class="search-input">
            <button class="search-button" type="submit">🔍 Найти</button>
        </div>
    </form>
   <!-- ПОЛЕ ПОИСКА ПЕСНИ ФИНИШ -->

    <!-- ФИЛЬТР ПО ЖАНРАМ СТАРТ -->
        <div class="music_category__styles">
            <strong>Жанры:</strong>
            <a class="music__category_buttons" href="{% url 'music:music' %}">Все</a>
            {% if genres %}
                {% for genre in genres %}
                    <a class="music__category_buttons" href="?genre={{ genre.id }}">
                        {{ genre.name }}
                    </a>
                {% endfor %}
            {% else %}
                <p>Нет жанров</p>
            {% endif %}
        </div>
    <!-- ФИЛЬТР ПО ЖАНРАМ ФИНИШ -->







    <!-- СПИСОК ПЕСЕН СТАРТ -->
    <h2 class="music__best-track">Популярные треки</h2>
    <div class="music__cards-wrapper">
        {% for song in songs %}
            <div class="music__card-wrapper">
                    <div class="music__imgs-wrapper">
                        {% if song.album.cover %}
                            <img class="music__img_song" src="{{ song.album.cover.url }}" 
                                 alt="{{ song.title}}">
                        {% else %}
                            <img class="music__img_song" src="{% static 'no-image.png' %}" alt="Нет изображения">
                        {% endif %}
                    </div>
                    <div class="music__song-wrapper">
                        <div class="music__info_song">
                            <h5 class="music__song-title">{{ song.title }}</h5>
                            <p class="music__song-info">
<!--                                <strong class="music__song-album"></strong> {{ song.album.title }} <br>-->
                                <strong class="music__song-artist"></strong> {{ song.artist.name}} <br>

<!--                                <strong class="music__song-genre">Жанр:</strong> {{ song.genre.name }}-->
                            </p>
                            {% if song.audio_file %}
                                <audio  class="music__song-audio" controls preload="none">
                                    <source src="{{ song.audio_file.url }}" type="audio/mpeg">
                                    Ваш браузер не поддерживает аудио.
                                </audio>
                            {% else %}
                                <p class="music__song-audio-absent">Аудиофайл отсутствует</p>
                            {% endif %}
                        </div>
                    </div>
                
            </div>
        {% empty %}
            <p class="music__no-songs-available">Тут такого нет ещё.</p>
        {% endfor %}
    </div>
    <!-- СПИСОК ПЕСЕН ФИНИШЬ -->




     <!-- АЛЬБОМЫ ФИНИШ -->
<!--    <h2 class="music__best-album">Популярные альбомы</h2>-->
<!--    <div class="music__cards-wrapper">-->


<!--        {% for album in albums %}-->
<!--            <div class="music__card-wrapper">-->
<!--                {% if album.cover %}-->
<!--                    <img class="music__img_album" src="{{ album.cover.url }}"  alt="{{ album.title }}">-->
<!--                {% else %}-->
<!--                    <img class="music__img_album" src="{% static 'no-image.png' %}" alt="Нет изображения">-->
<!--                {% endif %}-->
<!--                <h5 class="music__album-title">{{album.title}}</h5>-->
<!--                <a class="music__artist-title_link" href="{% url 'music:music' %}"></a>-->
<!--            </div>-->
<!--        {% endfor %}-->

<!--    </div>-->
    <!-- АЛЬБОМЫ ФИНИШ -->





    <!-- Популярные исполнители ФИНИШ -->
    <h2 class="music__best-artist">Популярные исполнители</h2>
    <div class="music__cards-wrapper">

        {% for artist in artists %}
            <div class="music__card-wrapper">
                    <div class="music__imgs-wrapper">
                            {% if artist.image %}
                                <img class="music__img_album" src="{{ artist.image.url }}"  alt="{{ album.title }}">
                            {% else %}
                                <img class="music__img_album" src="{% static 'no-image.png' %}" alt="Нет изображения">
                            {% endif %}
                    </div>
                    <div class="music__song-wrapper music__song-wrapper-link">
                        <h5 class="music__artist-title">{{ artist.name }}</h5>
                    </div>
                    <a class="music__artist-title_link" href="{% url 'music:artist_songs_view' artist.id %}">Подробнее</a>

            </div>
        {% endfor %}
    </div>
    <!-- Популярные исполнители ФИНИШ -->




    <!-- ПАГИНАЦИЯ СТАРТ -->
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a></li>
        {% endif %}
        {% for num_page in page_obj.paginator.page_range %}
          {% if num_page == page_obj.number %}
              <li class="page-item active"><a class="page-link" href="#">{{ num_page }}</a></li>
          {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a></li>
        {% endif %}
      </ul>
    </nav>
    <!-- ПАГИНАЦИЯ ФИНИШ -->
</div>

{% endblock %}